### ISSUE TITLE
not able to integrate in android.

### ISSUE THREAD

**Issue by singheshadev** [tradle/react-native-blinkid#1]
I am not able integrate in android.I have followed the instruction for manual integration. I have added my package.json file as follows: 

  "react-native-blinkid": "git+https://github.com/tradle/react-native-blinkid.git"

as I was not able to get the android version for:

"react-native-blinkid" : "^1.0.0".

However it is working fine for iOS but android is giving me following error:  

![screen shot 2017-05-01 at 3 58 20 pm](https://cloud.githubusercontent.com/assets/11420747/25577878/10dcad4e-2e87-11e7-84a5-4b74e93b88a6.png)

**Comment by Kenjirou** [comment]
Seems that there is no `android` folder in module's folder

**Comment by mvayngrib** [comment]
hey guys. I haven't published this to npm for a while, and the README could use some work. For now install from github

@singheshadev  you're probably missing this in the android/build.gradle (not android/app/build.gradle!)

```
allprojects {
    repositories {
...
        maven {
            url 'https://maven.microblink.com'
        }
    }
...
}
```

if that fixes things, I'll add it to the README (or feel free to submit a PR)

**Comment by mvayngrib** [comment]
btw, underneath this library uses the BlinkID SDK https://github.com/BlinkID/blinkid-android, which has been upgraded recently. See in addition their integration-via-gradle instructions if you get stuck: https://github.com/BlinkID/blinkid-android#using-gradle-or-android-studio

**Comment by Kenjirou** [comment]
@mvayngrib as I wrote earlier when I installed package through `yarn` there is no `android` folder in `react-native-blinkid`, only `ios`

**Comment by mvayngrib** [comment]
@Kenjirou install from github rather than npm, e.g.:

```
yarn add tradle/react-native-blinkid
yarn add https://github.com/tradle/react-native-blinkid
```

**Comment by Kenjirou** [comment]
@mvayngrib Yeah, sorry, forgot to remove folder in `node_modules`...
But now I have the same issue as **singheshadev**
![screenshot from 2017-06-05 17-57-56](https://cloud.githubusercontent.com/assets/13053189/26789384/ce00dd4e-4a18-11e7-841e-9c07856d2cfa.png)

**Comment by Kenjirou** [comment]
Ok, I'm only succeeded with build when I declared `compileSdkVersion 25`, `buildToolsVersion '25.0.3'` in `android` section and `compile 'com.android.support:appcompat-v7:25.+'` in dependencies of my `android/app/build.gradle`. Also I added `maven { url 'http://maven.microblink.com' }` to `android/app/build.gradle` in allprojects repositories.

**Comment by mvayngrib** [comment]
@Kenjirou cool, thanks for digging into that. I see in my own project, I have buildToolsVersion 25.0.1. Are you interested in making a PR to improve the README?

**Comment by Kenjirou** [comment]
@mvayngrib Yeah, sure

**Comment by mvayngrib** [comment]
closing, issue resolved by https://github.com/tradle/react-native-blinkid/pull/3
