### ISSUE TITLE
setKey is not a function

### ISSUE THREAD

**Issue by dhavrosh** [tradle/react-native-blinkid#2]
Hey guys,

I'm trying to integrate module into my ios-app, but i always get this error.
Pods i've installed

Can somebody help?

**Comment by mvayngrib** [comment]
@dhavrosh i think the method name is setLicenseKey not setKey

**Comment by dhavrosh** [comment]
No, I called setLicenseKey method and the error was about setKey

Now after linking and installing pods I've got build errors:

```
app/node_modules/react-native-blinkid/ios/RNBlinkIDOverlayViewController.m:19:14: error: property 'idCardSubview' not found on object of type 'RNBlinkIDOverlayViewController *'
        self.idCardSubview.tooltipLabel.text = self.customTooltipLabel;
             ^
app/node_modules/react-native-blinkid/ios/RNBlinkIDOverlayViewController.m:20:14: error: property 'idCardSubview' not found on object of type 'RNBlinkIDOverlayViewController *'
        self.idCardSubview.tooltipLabel.numberOfLines = 0;
             ^
app/node_modules/react-native-blinkid/ios/RNBlinkIDOverlayViewController.m:21:14: error: property 'idCardSubview' not found on object of type 'RNBlinkIDOverlayViewController *'
        self.idCardSubview.tooltipLabel.lineBreakMode = NSLineBreakByWordWrapping;
             ^
3 errors generated.
```
Project I've installed from github by "yarn add https://github.com/tradle/react-native-blinkid"

**Comment by mvayngrib** [comment]
@dhavrosh looking at the blinkid sdk installation [instructions](https://github.com/BlinkID/blinkid-ios#installation-with-cocoapods) , it could be because you don't have `git lfs`. What size do you see the MicroBlink.framework?

```sh
$ find . -name MicroBlink.framework -exec du -sh {} \;
170M	./iOS/Pods/PPBlinkID/MicroBlink.framework
```

If it's less than 100MB, this is probably the issue. Could you try following their setup instructions? Don't forget to clean your pods cache. Afterwards see if the framework file is the right size.

**Comment by dhavrosh** [comment]
Thanks a lot!

**Comment by mvayngrib** [comment]
@dhavrosh you're welcome :)

**Comment by Kenjirou** [comment]
@dhavrosh Can you please describe here all the steps to fix that issue? Because now I'm also have the same errors but MicroBlink.framework installed properly

**Comment by dhavrosh** [comment]
@Kenjirou I've got that problem because of `git lfs` ansence and just did what @mvayngrib has adviced

**Comment by Kenjirou** [comment]
@dhavrosh ok, thanks for the answer. I solved the issue when I changed the version of PPBlinkID in my Podfile from 2.5.1 to 2.9.0.
